-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) AS SALES
FROM PRODUCT AS A
INNER JOIN OFFLINE_SALE AS B
USING (PRODUCT_ID)
GROUP BY PRODUCT_ID, PRICE
ORDER BY SALES DESC, PRODUCT_CODE ASC;